services:
  # Spring Boot Application
  app:
    image: mohamedamineennour/kaddem:0.0.1
    container_name: kaddem-app
    ports:
      - "8089:8089"  # Exposing the Spring Boot app port
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/kaddem\db?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
    networks:
      - appnet
    restart: on-failure
    stdin_open: true
    tty: true
    depends_on:
      - mysql-db

  # MySQL Database
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kaddem
    ports:
      - "3306:3306"
    networks:
      - appnet
    volumes:
      - db:/var/lib/mysql

#Persistant volume for MySQL data
volumes:
  db:
networks:
  appnet:
    driver: bridge