services:
  # Spring Boot Application
  app:
    image: mohamedamineennour/kaddem:0.1.1
    container_name: kaddem-app
    ports:
      - "8089:8089"  # Exposing the Spring Boot app port
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/kaddem\db?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
    networks:
      - appnet
    depends_on:
      - mysql

  # MySQL Database
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=kaddem
    ports:
      - "3306:3306"
    networks:
      - appnet
    volumes:
      - mysql-data:/var/lib/mysql

#Persistant volume for MySQL data
volumes:
  mysql-data:
    driver: local
networks:
  appnet:
    driver: bridge